/**
 * place.config.ts — THE ingress for this instance's place identity.
 *
 * Everything place-specific (name, categories, map, feature toggles, SEO) lives
 * here. `src/` and `scripts/` stay generic and read from this file, so a single
 * file re-places the whole site. Generated by `npm run init` — the single
 * writer of this file. Edit values by hand freely after init; re-running the
 * wizard regenerates it (and reseeds knowledge/ with empty category folders).
 *
 * The `home` block ships generic defaults: no wizard prompt walks the home-page
 * copy. Replace it with place-specific copy by hand, or let the /adopt skill
 * draft it behind human approval.
 */

export interface PlaceConfig {
  place: {
    name: string;
    tagline: string;
    domain: string;
    locale: string;
    languages: string[];
  };
  /** 5-14 categories. slug/icon/description feed nav, hubs, and category pages. */
  categories: Array<{
    slug: string;
    title: string;
    icon: string;
    description: string;
  }>;
  /** Leaflet init: center [lat, lng], zoom, and maxBounds [[S,W],[N,E]]. */
  map: {
    center: [number, number];
    zoom: number;
    maxBounds: [[number, number], [number, number]];
  };
  features: {
    graph: boolean;
    map: boolean;
    dashboard: boolean;
    soundscape: boolean;
    feedback: boolean;
    chat: boolean;
    social: boolean;
    analytics: boolean;
  };
  /**
   * Outbound identity links. `repo` + `email` are always rendered (footer,
   * SEO sameAs/contactPoint, the "edit on GitHub" affordance). `social`
   * handles feed the footer social row and SEO sameAs, and render ONLY when
   * `features.social` is true. Handles include the leading `@`; component
   * code strips it when building platform URLs.
   */
  links: {
    repo: string;
    email: string;
    social: {
      twitter?: string;
      threads?: string;
      instagram?: string;
    };
  };
  seo: {
    defaultOgImage: string;
    twitterHandle?: string;
  };
  home: {
    hero: {
      subtitle: string;
      description: string;
      highlight: string;
      cta: { explore: string; github: string };
    };
    stats: Array<{ icon: string; number: string; label: string }>;
    doors: Array<{
      icon: string;
      href: string;
      title: string;
      sub: string;
      tone: 'green' | 'blue' | 'amber' | 'plum';
    }>;
    coverStory: {
      heading: string;
      lead: string;
      quotes: Array<{
        era: string;
        quote: string;
        cite: string;
      }>;
      closing: string[];
      aboutLinkText: string;
    };
    randomDiscovery: {
      button: string;
      subtitle: string;
      description: string;
    };
    features: {
      title: string;
      cards: Array<{ icon: string; title: string; description: string }>;
      cta: { graph: string; ssot: string };
    };
    exhibitions: {
      heading: string;
      divider: string;
      halls: Array<{
        label: string;
        paragraphs: Array<{
          text: string;
          pillHref: string;
          pillIcon: string;
          pillLabel: string;
          categorySlug: string;
        }>;
      }>;
    };
    recentUpdates: {
      heading: string;
      subtitle: string;
      viewAll: string;
      latestLabel: string;
    };
    contribute: {
      heading: string;
      description: string;
      guideLabel: string;
      githubLabel: string;
    };
  };
}

const config: PlaceConfig = {
  place: {
    name: 'Dana Point',
    tagline: 'Open-source, AI-friendly knowledge base for Dana Point.',
    domain: 'dana-point.42init.com',
    locale: 'en',
    languages: ['en'],
  },
  categories: [
    {
      slug: 'history',
      title: 'History',
      icon: '📜',
      description: 'Founding, growth, and the events that shaped the town',
    },
    {
      slug: 'beaches',
      title: 'Beaches',
      icon: '🏖️',
      description: 'Shoreline access, coves, tide pools, and swimming conditions',
    },
    {
      slug: 'nature',
      title: 'Nature',
      icon: '🌿',
      description: 'Habitats, wildlife, and protected areas',
    },
    {
      slug: 'trails',
      title: 'Trails',
      icon: '🥾',
      description: 'Hikes, walks, and viewpoints',
    },
    {
      slug: 'food',
      title: 'Food',
      icon: '🍽️',
      description: 'Restaurants, cafes, markets, and culinary landmarks',
    },
  ],
  map: {
    center: [33.467, -117.698],
    zoom: 13,
    maxBounds: [
      [33.417, -117.768],
      [33.517, -117.628],
    ],
  },
  features: {
    graph: true,
    map: true,
    dashboard: true,
    soundscape: false,
    feedback: false,
    chat: false,
    social: false,
    analytics: false,
  },
  links: {
    repo: 'https://github.com/wilsonkichoi/dana-point',
    email: 'hello@dana-point.42init.com',
    social: {},
  },
  seo: {
    defaultOgImage: '/og-default.png',
  },
  home: {
    hero: {
      subtitle: 'The only romantic spot on the coast.',
      description: 'An open-source knowledge base for Dana Point, California: the headland Richard Henry Dana described in 1840, the harbor built over Killer Dana in 1966, and the town that grew between them.',
      highlight: 'Sourced. Verified. Always evolving.',
      cta: {
        explore: 'Explore Topics',
        github: 'Star on GitHub',
      },
    },
    stats: [
      {
        icon: '📚',
        number: '5',
        label: 'knowledge domains',
      },
      {
        icon: '📝',
        number: 'Day 1',
        label: 'of the knowledge base',
      },
      {
        icon: '🔍',
        number: '100%',
        label: 'source-traced articles',
      },
      {
        icon: '🤖',
        number: '/kb',
        label: 'AI-readable endpoints',
      },
    ],
    doors: [
      {
        icon: '🚪',
        href: '#cover-story',
        title: 'First time here?',
        sub: 'Start with the story',
        tone: 'green',
      },
      {
        icon: '🔍',
        href: '/explore',
        title: 'Search everything',
        sub: 'Full-text across all articles',
        tone: 'blue',
      },
      {
        icon: '🎲',
        href: '#random-discovery',
        title: 'Surprise me',
        sub: 'Random deep-dive article',
        tone: 'amber',
      },
      {
        icon: '📊',
        href: '/dashboard',
        title: 'Site health',
        sub: 'Freshness and coverage stats',
        tone: 'plum',
      },
    ],
    coverStory: {
      heading: 'The Story So Far',
      lead: 'A hide-trade anchorage, a surf break, a harbor town. This knowledge base holds the sourced, verified record of Dana Point from Toovannga to today.',
      quotes: [
        {
          era: 'Then',
          quote: 'The only romantic spot on the coast.',
          cite: 'Richard Henry Dana Jr., Two Years Before the Mast (1840)',
        },
        {
          era: 'Now',
          quote: 'Whale Heritage Site, home of the world\'s first surf shop, and 33,107 people living on the bluffs where hides once flew off the cliff.',
          cite: 'World Cetacean Alliance (2021); Hobie Alter, 1954; US Census 2020',
        },
        {
          era: '.md',
          quote: 'This knowledge base exists to document all of it: sourced, verified, and open for anyone to read or improve.',
          cite: 'Project mission statement',
        },
      ],
      closing: [
        'Every article in this knowledge base traces back to sources.',
        'The goal is not promotion. The goal is the most complete, accurate account of this place that exists anywhere.',
      ],
      aboutLinkText: 'Read the full story',
    },
    randomDiscovery: {
      button: 'Roll the dice',
      subtitle: 'Random deep-dive article',
      description: 'Every article has footnotes. Hit the button and land somewhere you did not expect.',
    },
    features: {
      title: 'What Makes This Different',
      cards: [
        {
          icon: '🎯',
          title: 'Curated, Not Scraped',
          description: 'Every article is written and fact-checked by hand, not generated from search results.',
        },
        {
          icon: '🤖',
          title: 'AI-Friendly',
          description: 'Structured endpoints at /kb/ and /llms.txt for LLM consumption. Built for machines and humans.',
        },
        {
          icon: '🔍',
          title: 'Source-Traced',
          description: 'Footnotes cite sources. Claims link to evidence. Verification dates are visible.',
        },
        {
          icon: '📚',
          title: 'Comprehensive',
          description: '5 domains covering the full spectrum: history, beaches, nature, trails, food.',
        },
      ],
      cta: {
        graph: 'Explore the Knowledge Graph',
        ssot: 'View Raw Knowledge',
      },
    },
    exhibitions: {
      heading: 'Exhibition Halls',
      divider: 'All Categories',
      halls: [
        {
          label: 'I — History & Beaches',
          paragraphs: [
            {
              text: 'From the Acjachemen village of Toovannga through the hide trade, Lantern Village development, and the harbor that buried Killer Dana. The full timeline, sourced.',
              pillHref: '/history',
              pillIcon: '📜',
              pillLabel: 'History',
              categorySlug: 'history',
            },
            {
              text: 'Doheny, Strands, Salt Creek, Capistrano Beach: access points, conditions, tide pools, and the funicular that finally got people down the bluff.',
              pillHref: '/beaches',
              pillIcon: '🏖️',
              pillLabel: 'Beaches',
              categorySlug: 'beaches',
            },
          ],
        },
        {
          label: 'II — Nature & Trails',
          paragraphs: [
            {
              text: 'Headlands conservation area, the lost coastal plants, kelp beds offshore, and the juvenile great whites that hunt the shallows.',
              pillHref: '/nature',
              pillIcon: '🌿',
              pillLabel: 'Nature',
              categorySlug: 'nature',
            },
            {
              text: 'Bluff-top walks with Catalina views, the Headlands nature center loop, and the stairways that connect the town to the shore.',
              pillHref: '/trails',
              pillIcon: '🥾',
              pillLabel: 'Trails',
              categorySlug: 'trails',
            },
          ],
        },
        {
          label: 'III — Food',
          paragraphs: [
            {
              text: 'The harbor restaurants, Lantern Village cafes, and the places locals actually eat. Opening status and parking realities included.',
              pillHref: '/food',
              pillIcon: '🍽️',
              pillLabel: 'Food',
              categorySlug: 'food',
            },
          ],
        },
      ],
    },
    recentUpdates: {
      heading: 'Recent Updates',
      subtitle: 'Latest changes to the knowledge base',
      viewAll: 'View All Changes',
      latestLabel: 'Latest Articles',
    },
    contribute: {
      heading: 'Contribute',
      description: 'This is an open-source project. Every article, every source, every line of code is public. If you know something we missed, you can fix it.',
      guideLabel: 'Contribution Guide',
      githubLabel: 'View on GitHub',
    },
  },
};

export default config;
